language: csharp
mono: none
dist: xenial
dotnet: 3.1
solution: NPFTestApi.sln
script:
  - dotnet restore
  - dotnet build
  - dotnet test tests/NPFTestApi.Tests/NPFTestApi.Tests.csproj
on:
  tags: true